### ISSUE TITLE
Assign users bug

### ISSUE THREAD

**Issue by Alchez** [agritheory/approvals#60]
### App Versions
```
{
	"approvals": "14.2.1",
	"erpnext": "14.70.11",
	"frappe": "14.78.0",
	"hrms": "14.29.0"
}
```
### Route
```
Form/Purchase Invoice/ACC-PINV-2024-00006
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 97, in application
    response = frappe.api.handle()
               ^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 48, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1619, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/approvals/approvals/approvals/api.py", line 64, in fetch_approvals_and_roles
    roles = get_approval_roles(doc)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/approvals/approvals/approvals/api.py", line 18, in get_approval_roles
    roles = [
            ^
  File "apps/approvals/approvals/approvals/api.py", line 25, in <listcomp>
    ).apply(doc)
      ^^^^^^^^^^
  File "apps/approvals/approvals/approvals/doctype/document_approval_rule/document_approval_rule.py", line 45, in apply
    if result and self.assign_users:
                  ^^^^^^^^^^^^^^^^^
AttributeError: 'DocumentApprovalRule' object has no attribute 'assign_users'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"ACC-PINV-2024-00006\",\"owner\":\"Administrator\",\"creation\":\"2024-06-21 07:59:17.545501\",\"modified\":\"2024-06-21 07:59:17.545501\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":0,\"title\":\"Sphere Cellular\",\"naming_series\":\"ACC-PINV-.YYYY.-\",\"supplier\":\"Sphere Cellular\",\"supplier_name\":\"Sphere Cellular\",\"company\":\"Chelsea Fruit Co\",\"posting_date\":\"2024-01-01\",\"posting_time\":\"7:59:17.543629\",\"set_posting_time\":1,\"due_date\":\"2024-01-01\",\"is_paid\":0,\"is_return\":0,\"update_outstanding_for_self\":1,\"update_billed_amount_in_purchase_order\":0,\"update_billed_amount_in_purchase_receipt\":1,\"apply_tds\":0,\"currency\":\"USD\",\"conversion_rate\":1,\"use_transaction_date_exchange_rate\":0,\"buying_price_list\":\"Standard Buying\",\"price_list_currency\":\"USD\",\"plc_conversion_rate\":1,\"ignore_pricing_rule\":0,\"update_stock\":0,\"is_subcontracted\":0,\"total_qty\":1,\"total_net_weight\":0,\"base_total\":250,\"base_net_total\":250,\"total\":250,\"net_total\":250,\"tax_withholding_net_total\":250,\"base_tax_withholding_net_total\":250,\"tax_category\":\"\",\"base_taxes_and_charges_added\":0,\"base_taxes_and_charges_deducted\":0,\"base_total_taxes_and_charges\":0,\"taxes_and_charges_added\":0,\"taxes_and_charges_deducted\":0,\"total_taxes_and_charges\":0,\"base_grand_total\":250,\"base_rounding_adjustment\":0,\"base_rounded_total\":250,\"base_in_words\":\"USD Two Hundred And Fifty only.\",\"grand_total\":250,\"rounding_adjustment\":0,\"use_company_roundoff_cost_center\":0,\"rounded_total\":250,\"in_words\":\"USD Two Hundred And Fifty only.\",\"total_advance\":0,\"outstanding_amount\":250,\"disable_rounded_total\":0,\"apply_discount_on\":\"Grand Total\",\"base_discount_amount\":0,\"additional_discount_percentage\":0,\"discount_amount\":0,\"base_paid_amount\":0,\"paid_amount\":0,\"allocate_advances_automatically\":0,\"only_include_allocated_payments\":0,\"write_off_amount\":0,\"base_write_off_amount\":0,\"ignore_default_payment_terms_template\":0,\"status\":\"Draft\",\"per_received\":0,\"credit_to\":\"2110 - Creditors - CFC\",\"party_account_currency\":\"USD\",\"is_opening\":\"No\",\"against_expense_account\":\"2210 - Stock Received But Not Billed - CFC\",\"repost_required\":0,\"group_same_items\":0,\"language\":\"en\",\"on_hold\":0,\"is_internal_supplier\":0,\"represents_company\":\"\",\"is_old_subcontracting_flow\":0,\"remarks\":\"No Remarks\",\"doctype\":\"Purchase Invoice\",\"pricing_rules\":[],\"tax_withheld_vouchers\":[],\"advance_tax\":[],\"taxes\":[],\"payment_schedule\":[{\"name\":\"cbmosrq6q0\",\"owner\":\"Administrator\",\"creation\":\"2024-06-21 07:59:17.601110\",\"modified\":\"2024-06-21 07:59:17.601110\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"due_date\":\"2024-01-01\",\"invoice_portion\":100,\"discount\":0,\"payment_amount\":250,\"outstanding\":250,\"paid_amount\":0,\"discounted_amount\":0,\"base_payment_amount\":250,\"parent\":\"ACC-PINV-2024-00006\",\"parentfield\":\"payment_schedule\",\"parenttype\":\"Purchase Invoice\",\"doctype\":\"Payment Schedule\"}],\"advances\":[],\"supplied_items\":[],\"items\":[{\"name\":\"cbmnp47b2k\",\"owner\":\"Administrator\",\"creation\":\"2024-06-21 07:59:17.545501\",\"modified\":\"2024-06-21 07:59:17.545501\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"item_code\":\"Phone Services\",\"item_name\":\"Phone Services\",\"description\":\"Phone Services\",\"item_group\":\"Services\",\"image\":\"\",\"received_qty\":0,\"qty\":1,\"rejected_qty\":0,\"uom\":\"Nos\",\"conversion_factor\":1,\"stock_uom\":\"Nos\",\"stock_qty\":1,\"price_list_rate\":0,\"base_price_list_rate\":0,\"margin_type\":\"\",\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_percentage\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":250,\"amount\":250,\"base_rate\":250,\"base_amount\":250,\"stock_uom_rate\":250,\"is_free_item\":0,\"apply_tds\":1,\"net_rate\":250,\"net_amount\":250,\"base_net_rate\":250,\"base_net_amount\":250,\"valuation_rate\":250,\"item_tax_amount\":0,\"landed_cost_voucher_amount\":0,\"rm_supp_cost\":0,\"warehouse\":\"Stores - CFC\",\"expense_account\":\"2210 - Stock Received But Not Billed - CFC\",\"is_fixed_asset\":0,\"enable_deferred_expense\":0,\"allow_zero_valuation_rate\":0,\"item_tax_rate\":\"{}\",\"include_exploded_items\":0,\"weight_per_unit\":0,\"total_weight\":0,\"cost_center\":\"Main - CFC\",\"page_break\":0,\"parent\":\"ACC-PINV-2024-00006\",\"parentfield\":\"items\",\"parenttype\":\"Purchase Invoice\",\"doctype\":\"Purchase Invoice Item\"}],\"__onload\":{\"make_payment_via_journal_entry\":0,\"backflush_based_on\":\"BOM\",\"supplier_tds\":null},\"__last_sync_on\":\"2024-07-22T06:45:26.383Z\"}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/approvals.approvals.api.fetch_approvals_and_roles"
}
```
### Response Data
```
{
	"exception": "AttributeError: 'DocumentApprovalRule' object has no attribute 'assign_users'"
}
```

**Comment by Alchez** [comment]
@agritheory I'm not sure if this is still a relevant issue in v15, but I'm noting it here just in case.
